"""add source and target interface to design relationships

Revision ID: 071ff4ab5de0
Revises: a2c8e1f7b930
Create Date: 2026-09-17 08:50:06.163946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '071ff4ab5de0'
down_revision: Union[str, None] = 'a2c8e1f7b930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_relationships', sa.Column('source_interface', sa.String(length=150), nullable=True))
    op.add_column('design_relationships', sa.Column('target_interface', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('design_relationships', 'target_interface')
    op.drop_column('design_relationships', 'source_interface')
    # ### end Alembic commands ###
