"""add configuration versioning and drift domains

Revision ID: 14b9fdf9aaf3
Revises: 354303067e7a
Create Date: 2026-08-18 21:29:30.009647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '14b9fdf9aaf3'
down_revision: Union[str, None] = '354303067e7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drift_runs',
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='drift_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assets_checked', sa.Integer(), nullable=False),
    sa.Column('drift_found_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_results',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('expected_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='drift_severity'), nullable=False),
    sa.Column('status', sa.Enum('new', 'accepted', 'ignored', 'remediated', name='drift_status'), nullable=False),
    sa.Column('ignore_reason', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['drift_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_versions',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('configuration_object_id', sa.UUID(), nullable=False),
    sa.Column('deployment_job_id', sa.UUID(), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['configuration_object_id'], ['configuration_objects.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deployment_job_id'], ['deployment_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'technology', 'object_type', 'version_number', name='uq_config_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration_versions')
    op.drop_table('drift_results')
    op.drop_table('drift_runs')
    # ### end Alembic commands ###

    sa.Enum(name='drift_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='drift_severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='drift_run_status').drop(op.get_bind(), checkfirst=True)
