"""add approval, backup, and deployment domains

Revision ID: 354303067e7a
Revises: 8047fae10553
Create Date: 2026-08-18 21:05:39.873251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '354303067e7a'
down_revision: Union[str, None] = '8047fae10553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('configuration_job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_request_status'), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('required_approvals', sa.Integer(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_job_id'], ['configuration_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_job_id')
    )
    op.create_table('backups',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('backup_type', sa.Enum('manual', 'scheduled', 'pre_deployment', 'post_deployment', name='backup_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('deployment_job_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_jobs',
    sa.Column('configuration_job_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'precheck', 'precheck_failed', 'backup', 'backup_failed', 'applying', 'apply_failed', 'verifying', 'verify_failed', 'success', 'rolling_back', 'rolled_back', 'rollback_failed', name='deployment_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['configuration_job_id'], ['configuration_jobs.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_actions',
    sa.Column('approval_request_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('approve', 'reject', name='approval_action_type'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('acted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_events',
    sa.Column('deployment_job_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_job_id'], ['deployment_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_results',
    sa.Column('deployment_job_id', sa.UUID(), nullable=False),
    sa.Column('configuration_object_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verify_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['configuration_object_id'], ['configuration_objects.id'], ),
    sa.ForeignKeyConstraint(['deployment_job_id'], ['deployment_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_targets',
    sa.Column('deployment_job_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['deployment_job_id'], ['deployment_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_locks',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('lock_type', sa.String(length=30), nullable=False),
    sa.Column('deployment_job_id', sa.UUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deployment_job_id'], ['deployment_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'lock_type'),
    sa.UniqueConstraint('asset_id', 'lock_type', name='uq_resource_lock_asset_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_locks')
    op.drop_table('deployment_targets')
    op.drop_table('deployment_results')
    op.drop_table('deployment_events')
    op.drop_table('approval_actions')
    op.drop_table('deployment_jobs')
    op.drop_table('backups')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###

    sa.Enum(name='deployment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='backup_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='approval_action_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='approval_request_status').drop(op.get_bind(), checkfirst=True)
