"""add login lockout fields to users

Revision ID: 3fd72dbec4e2
Revises: 14b9fdf9aaf3
Create Date: 2026-08-18 21:49:47.268066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fd72dbec4e2'
down_revision: Union[str, None] = '14b9fdf9aaf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0')
    )
    op.alter_column('users', 'failed_login_attempts', server_default=None)
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    # ### end Alembic commands ###
