"""add architecture design domain

Revision ID: 489cfdf06a34
Revises: 775503e0ddd9
Create Date: 2026-08-18 20:39:42.349899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '489cfdf06a34'
down_revision: Union[str, None] = '775503e0ddd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_designs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mode', sa.Enum('best_practice_assisted', 'manual', name='design_mode'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('architecture_design_versions',
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'under_review', 'approved', 'superseded', 'archived', name='design_version_status'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['architecture_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id', 'version_number', name='uq_design_version_number')
    )
    op.create_table('design_approvals',
    sa.Column('design_version_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['design_version_id'], ['architecture_design_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_components',
    sa.Column('design_version_id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['design_version_id'], ['architecture_design_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('design_recommendation_mappings',
    sa.Column('design_version_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['design_version_id'], ['architecture_design_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['architecture_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('design_version_id', 'finding_id')
    )
    op.create_table('design_asset_mappings',
    sa.Column('design_component_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['design_component_id'], ['design_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('design_component_id', 'asset_id')
    )
    op.create_table('design_relationships',
    sa.Column('design_version_id', sa.UUID(), nullable=False),
    sa.Column('source_component_id', sa.UUID(), nullable=False),
    sa.Column('target_component_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['design_version_id'], ['architecture_design_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_component_id'], ['design_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_component_id'], ['design_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design_relationships')
    op.drop_table('design_asset_mappings')
    op.drop_table('design_recommendation_mappings')
    op.drop_table('design_components')
    op.drop_table('design_approvals')
    op.drop_table('architecture_design_versions')
    op.drop_table('architecture_designs')
    # ### end Alembic commands ###

    sa.Enum(name='design_version_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='design_mode').drop(op.get_bind(), checkfirst=True)
