"""add remediation_job_id link to drift results

Revision ID: 546fda5bb3b2
Revises: 3fd72dbec4e2
Create Date: 2026-08-18 21:55:23.874601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '546fda5bb3b2'
down_revision: Union[str, None] = '3fd72dbec4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_results', sa.Column('remediation_job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'drift_results_remediation_job_id_fkey',
        'drift_results',
        'configuration_jobs',
        ['remediation_job_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('drift_results_remediation_job_id_fkey', 'drift_results', type_='foreignkey')
    op.drop_column('drift_results', 'remediation_job_id')
    # ### end Alembic commands ###
