"""add safe_pin classification to assets

Revision ID: 65faefaf880e
Revises: 546fda5bb3b2
Create Date: 2026-09-07 21:38:42.974842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65faefaf880e'
down_revision: Union[str, None] = '546fda5bb3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Unlike enum columns added inside op.create_table (which compiles the CREATE TYPE
    # automatically), add_column on an existing table needs the type created explicitly first.
    safe_pin_enum = sa.Enum(
        'internet_edge', 'wan', 'campus_core', 'campus_distribution', 'campus_access',
        'data_center', 'branch', 'cloud', 'management', name='safe_pin',
    )
    safe_pin_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('assets', sa.Column('safe_pin', safe_pin_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'safe_pin')
    # ### end Alembic commands ###
    sa.Enum(name='safe_pin').drop(op.get_bind(), checkfirst=True)
