"""add best practice rule engine and architecture findings

Revision ID: 775503e0ddd9
Revises: e9baa225bcb6
Create Date: 2026-08-18 20:33:57.455563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '775503e0ddd9'
down_revision: Union[str, None] = 'e9baa225bcb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_practice_runs',
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='best_practice_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rules_evaluated', sa.Integer(), nullable=False),
    sa.Column('findings_created', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('architecture_findings',
    sa.Column('finding_code', sa.String(length=50), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('rule_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='finding_severity'), nullable=False),
    sa.Column('current_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_review', 'accepted', 'ignored', 'remediated', 'closed', name='finding_status'), nullable=False),
    sa.Column('ignore_reason', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['best_practice_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_code')
    )
    op.create_table('finding_assets',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['architecture_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', 'asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finding_assets')
    op.drop_table('architecture_findings')
    op.drop_table('best_practice_runs')
    # ### end Alembic commands ###

    sa.Enum(name='finding_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='finding_severity').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='best_practice_run_status').drop(op.get_bind(), checkfirst=True)
