"""add configuration core and profiles

Revision ID: 8047fae10553
Revises: 489cfdf06a34
Create Date: 2026-08-18 20:51:39.373579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8047fae10553'
down_revision: Union[str, None] = '489cfdf06a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration_profiles',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('parameters_template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'testing', 'published', 'deprecated', name='profile_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_profile_name_version')
    )
    op.create_table('configuration_jobs',
    sa.Column('job_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('design', 'manual', name='config_source_type'), nullable=False),
    sa.Column('source_design_version_id', sa.UUID(), nullable=True),
    sa.Column('justification_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'generated', 'validating', 'validated', 'pending_approval', 'approved', 'rejected', 'ready', 'failed', name='config_job_status'), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'critical', name='config_risk_level'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['asset_environments.id'], ),
    sa.ForeignKeyConstraint(['source_design_version_id'], ['architecture_design_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_number')
    )
    op.create_table('configuration_job_targets',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['configuration_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'asset_id')
    )
    op.create_table('configuration_objects',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_type', sa.Enum('create', 'update', 'delete', 'no_change', name='config_change_type'), nullable=True),
    sa.Column('validation_status', sa.Enum('pending', 'pass', 'warning', 'high', 'critical', name='config_validation_status'), nullable=False),
    sa.Column('validation_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rendered_operations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['configuration_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuration_object_dependencies',
    sa.Column('parent_object_id', sa.UUID(), nullable=False),
    sa.Column('child_object_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['child_object_id'], ['configuration_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_object_id'], ['configuration_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_object_id', 'child_object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration_object_dependencies')
    op.drop_table('configuration_objects')
    op.drop_table('configuration_job_targets')
    op.drop_table('configuration_jobs')
    op.drop_table('configuration_profiles')
    # ### end Alembic commands ###

    sa.Enum(name='config_validation_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='config_change_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='config_risk_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='config_job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='config_source_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='profile_status').drop(op.get_bind(), checkfirst=True)
