"""add discovery and topology domains

Revision ID: e9baa225bcb6
Revises: 6445bda8f4c3
Create Date: 2026-08-18 20:20:49.043518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e9baa225bcb6'
down_revision: Union[str, None] = '6445bda8f4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topology_nodes',
    sa.Column('node_type', sa.Enum('device', 'server', 'service', 'zone', 'site', 'cloud', 'network', 'subnet', 'application', name='topology_node_type'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('node_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_type', 'reference_id', name='uq_topology_node_reference')
    )
    op.create_table('topology_views',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('view_type', sa.Enum('physical', 'logical', 'layer2', 'layer3', 'security', 'service', 'application_dependency', 'site', 'zone', name='topology_view_type'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('discovery_jobs',
    sa.Column('method', sa.Enum('manual', 'csv_import', 'api_import', 'network_scan', 'snmp', 'ssh', 'winrm', 'rest_api', 'netconf', 'restconf', 'cloud_api', name='discovery_method'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'partial', 'success', 'failed', 'cancelled', name='discovery_job_status'), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credential_profile_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credential_profile_id'], ['credential_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topology_layouts',
    sa.Column('view_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['view_id'], ['topology_views.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('view_id', 'node_id')
    )
    op.create_table('topology_links',
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('destination_node_id', sa.UUID(), nullable=False),
    sa.Column('source_interface', sa.String(length=150), nullable=True),
    sa.Column('destination_interface', sa.String(length=150), nullable=True),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('speed_mbps', sa.Integer(), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('subnet', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('discovery_source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_targets',
    sa.Column('discovery_job_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_errors',
    sa.Column('discovery_job_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['discovery_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_results',
    sa.Column('discovery_job_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['discovery_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discovery_results')
    op.drop_table('discovery_errors')
    op.drop_table('discovery_targets')
    op.drop_table('topology_links')
    op.drop_table('topology_layouts')
    op.drop_table('discovery_jobs')
    op.drop_table('topology_views')
    op.drop_table('topology_nodes')
    # ### end Alembic commands ###

    # Postgres ENUM types survive drop_table and must be dropped explicitly (see the
    # initial migration for why) or upgrade() fails on the next run.
    sa.Enum(name='discovery_job_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='discovery_method').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='topology_view_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='topology_node_type').drop(op.get_bind(), checkfirst=True)
